export const ELEMENT_REMOVE = 'ELEMENT_REMOVE';
export const ELEMENT_SET = 'ELEMENT_SET';
export const ELEMENTS_RESET = 'ELEMENTS_RESET';
export const VIEW_FILTERS_SET = 'VIEW_FILTERS_SET';
export const YEARS_SET = 'YEARS_SET';
